name: "coihuin-compress"
description: "A Claude Code skill that proactively compresses context windows to maintain work state with minimal token usage while preserving precise information."
purpose: "Preserve critical work state during long coding sessions by intelligently compressing context, preventing information loss when automatic summarization occurs."
created: 2025-12-14

scope:
  includes:
    - Context compression algorithms and strategies
    - Work state tracking and preservation
    - Checkpoint/snapshot generation
    - Delta tracking between checkpoints
    - Token-efficient state representation
    - Claude Code skill integration
  excludes:
    - External API calls
    - Persistent database storage
    - User code modification
    - Network requests to third-party services

tech_stack:
  languages:
    - Markdown
  frameworks:
    - Claude Code Skills
  dependencies:
    - Claude Code CLI

stakeholders:
  - Claude Code users with long coding sessions
  - Developers working on complex multi-file changes
  - Users concerned about context window limitations

methodology: spec-driven
version: 0.1.0
